#!/usr/bin/env ansible-playbook
# vim:ft=ansible:
- name: Configure Bind Server
  hosts: dnshosts
  vars:
    zonename: "myexample.com"

    dns:
      clients:
        - 10.0.0.0/8
        - 192.168.0.0/16
      nameservers:
        ns1:
          ip_address: 10.20.30.100
      zones:
        "myexample.com":
          local: True

  roles:
    - role: loginpreferences
    - role: loginpreferences
      sudo: True
    - role: workdir
    - role: aptup
    - role: bindapt
    - role: bindsetup
