#!/usr/bin/env ansible-playbook
# vim:ft=ansible:
- name: Configure Bind Server
  hosts: dnshosts
  vars:
    dns:
      ns1:
        ip_address: 1.2.3.4
      ns2:
        ip_address: 2.3.4.5
  roles:
    - role: loginpreferences
    - role: loginpreferences
      sudo: True
    - role: workdir
    - role: aptup
    - role: bindapt
    - role: bindsetup

